import { useState } from "react";
import { motion } from "framer-motion";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { Copy, Download, FileText, Plus, X, Bot, Shield, Globe } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface Rule {
  userAgent: string;
  allow: string[];
  disallow: string[];
}

const RobotsTxtGenerator = () => {
  const { toast } = useToast();
  const [sitemapUrl, setSitemapUrl] = useState("");
  const [crawlDelay, setCrawlDelay] = useState("");
  const [rules, setRules] = useState<Rule[]>([
    { userAgent: "*", allow: ["/"], disallow: [] }
  ]);
  const [commonDisallows, setCommonDisallows] = useState({
    admin: false,
    api: false,
    private: false,
    cgibin: false,
    wp: false,
    search: false
  });

  const addRule = () => {
    setRules([...rules, { userAgent: "", allow: [], disallow: [] }]);
  };

  const removeRule = (index: number) => {
    setRules(rules.filter((_, i) => i !== index));
  };

  const updateRule = (index: number, field: keyof Rule, value: string | string[]) => {
    const updated = [...rules];
    updated[index] = { ...updated[index], [field]: value };
    setRules(updated);
  };

  const addPath = (ruleIndex: number, type: 'allow' | 'disallow') => {
    const updated = [...rules];
    updated[ruleIndex][type] = [...updated[ruleIndex][type], ""];
    setRules(updated);
  };

  const updatePath = (ruleIndex: number, type: 'allow' | 'disallow', pathIndex: number, value: string) => {
    const updated = [...rules];
    updated[ruleIndex][type][pathIndex] = value;
    setRules(updated);
  };

  const removePath = (ruleIndex: number, type: 'allow' | 'disallow', pathIndex: number) => {
    const updated = [...rules];
    updated[ruleIndex][type] = updated[ruleIndex][type].filter((_, i) => i !== pathIndex);
    setRules(updated);
  };

  const generateRobotsTxt = () => {
    let output = "# Robots.txt generated by DigiSpark Tools\n";
    output += "# https://digispark.com/tools\n\n";

    rules.forEach(rule => {
      output += `User-agent: ${rule.userAgent || "*"}\n`;
      
      rule.allow.forEach(path => {
        if (path) output += `Allow: ${path}\n`;
      });
      
      rule.disallow.forEach(path => {
        if (path) output += `Disallow: ${path}\n`;
      });

      // Add common disallows
      if (commonDisallows.admin) output += "Disallow: /admin/\n";
      if (commonDisallows.api) output += "Disallow: /api/\n";
      if (commonDisallows.private) output += "Disallow: /private/\n";
      if (commonDisallows.cgibin) output += "Disallow: /cgi-bin/\n";
      if (commonDisallows.wp) output += "Disallow: /wp-admin/\n";
      if (commonDisallows.search) output += "Disallow: /search\n";

      if (crawlDelay) {
        output += `Crawl-delay: ${crawlDelay}\n`;
      }
      
      output += "\n";
    });

    if (sitemapUrl) {
      output += `Sitemap: ${sitemapUrl}\n`;
    }

    return output;
  };

  const robotsTxt = generateRobotsTxt();

  const copyToClipboard = () => {
    navigator.clipboard.writeText(robotsTxt);
    toast({
      title: "Copied!",
      description: "Robots.txt copied to clipboard",
    });
  };

  const downloadFile = () => {
    const blob = new Blob([robotsTxt], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "robots.txt";
    a.click();
    URL.revokeObjectURL(url);
    toast({
      title: "Downloaded!",
      description: "Robots.txt file downloaded successfully",
    });
  };

  return (
    <Card className="border-yellow-400/20 bg-black/50 backdrop-blur-md">
      <CardContent className="p-6">
        <div className="flex items-center gap-3 mb-6">
          <div className="p-3 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-500">
            <Bot className="w-6 h-6 text-white" />
          </div>
          <div>
            <h3 className="text-2xl font-bold text-white">Robots.txt Generator</h3>
            <p className="text-gray-400 text-base">Create a valid robots.txt file to control search engine crawlers</p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Configuration Section */}
          <div className="space-y-6">
            {/* Sitemap URL */}
            <div className="space-y-2">
              <Label className="text-white text-base flex items-center gap-2">
                <Globe className="w-4 h-4 text-yellow-400" />
                Sitemap URL
              </Label>
              <Input
                placeholder="https://yoursite.com/sitemap.xml"
                value={sitemapUrl}
                onChange={(e) => setSitemapUrl(e.target.value)}
                className="bg-gray-800/50 text-white border-gray-700 text-base"
              />
            </div>

            {/* Crawl Delay */}
            <div className="space-y-2">
              <Label className="text-white text-base">Crawl Delay (seconds)</Label>
              <Input
                type="number"
                placeholder="10"
                value={crawlDelay}
                onChange={(e) => setCrawlDelay(e.target.value)}
                className="bg-gray-800/50 text-white border-gray-700 text-base w-32"
              />
            </div>

            {/* Common Disallow Options */}
            <div className="space-y-3">
              <Label className="text-white text-base flex items-center gap-2">
                <Shield className="w-4 h-4 text-yellow-400" />
                Quick Disallow Options
              </Label>
              <div className="grid grid-cols-2 gap-3">
                {Object.entries({
                  admin: "/admin/",
                  api: "/api/",
                  private: "/private/",
                  cgibin: "/cgi-bin/",
                  wp: "/wp-admin/",
                  search: "/search"
                }).map(([key, path]) => (
                  <div key={key} className="flex items-center space-x-2">
                    <Checkbox
                      id={key}
                      checked={commonDisallows[key as keyof typeof commonDisallows]}
                      onCheckedChange={(checked) => 
                        setCommonDisallows(prev => ({ ...prev, [key]: !!checked }))
                      }
                      className="border-gray-600 data-[state=checked]:bg-yellow-400"
                    />
                    <label htmlFor={key} className="text-gray-300 cursor-pointer text-base">
                      {path}
                    </label>
                  </div>
                ))}
              </div>
            </div>

            {/* Rules */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <Label className="text-white text-base">Custom Rules</Label>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={addRule}
                  className="border-yellow-400/50 text-yellow-400 hover:bg-yellow-400/10"
                >
                  <Plus className="w-4 h-4 mr-1" />
                  Add Rule
                </Button>
              </div>

              {rules.map((rule, ruleIndex) => (
                <motion.div
                  key={ruleIndex}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="bg-gray-800/30 rounded-lg p-4 space-y-3 border border-gray-700/50"
                >
                  <div className="flex items-center gap-2">
                    <Input
                      placeholder="User-agent (e.g., * or Googlebot)"
                      value={rule.userAgent}
                      onChange={(e) => updateRule(ruleIndex, 'userAgent', e.target.value)}
                      className="bg-gray-900/50 text-white border-gray-600 text-base"
                    />
                    {rules.length > 1 && (
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => removeRule(ruleIndex)}
                        className="text-red-400 hover:text-red-300 hover:bg-red-400/10"
                      >
                        <X className="w-4 h-4" />
                      </Button>
                    )}
                  </div>

                  {/* Disallow paths */}
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="text-gray-400 text-base">Disallow paths:</span>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => addPath(ruleIndex, 'disallow')}
                        className="text-yellow-400 hover:text-yellow-300 text-base"
                      >
                        <Plus className="w-3 h-3 mr-1" />
                        Add
                      </Button>
                    </div>
                    {rule.disallow.map((path, pathIndex) => (
                      <div key={pathIndex} className="flex items-center gap-2">
                        <Input
                          placeholder="/path/"
                          value={path}
                          onChange={(e) => updatePath(ruleIndex, 'disallow', pathIndex, e.target.value)}
                          className="bg-gray-900/50 text-white border-gray-600 text-base"
                        />
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => removePath(ruleIndex, 'disallow', pathIndex)}
                          className="text-red-400 hover:text-red-300"
                        >
                          <X className="w-3 h-3" />
                        </Button>
                      </div>
                    ))}
                  </div>
                </motion.div>
              ))}
            </div>
          </div>

          {/* Preview Section */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <Label className="text-white text-base flex items-center gap-2">
                <FileText className="w-4 h-4 text-yellow-400" />
                Generated robots.txt
              </Label>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={copyToClipboard}
                  className="border-yellow-400/50 text-yellow-400 hover:bg-yellow-400/10"
                >
                  <Copy className="w-4 h-4 mr-1" />
                  Copy
                </Button>
                <Button
                  size="sm"
                  onClick={downloadFile}
                  className="bg-yellow-400 hover:bg-yellow-300 text-black"
                >
                  <Download className="w-4 h-4 mr-1" />
                  Download
                </Button>
              </div>
            </div>

            <Textarea
              value={robotsTxt}
              readOnly
              className="h-80 font-mono text-base bg-gray-900/50 text-emerald-400 border-gray-700"
            />

            <div className="bg-gray-800/30 rounded-lg p-4 border border-gray-700/50">
              <h4 className="text-yellow-400 font-semibold mb-2 text-base">📌 How to Use</h4>
              <ol className="text-gray-300 space-y-1 list-decimal list-inside text-base">
                <li>Download the generated robots.txt file</li>
                <li>Upload it to your website's root directory</li>
                <li>Test using Google Search Console</li>
              </ol>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default RobotsTxtGenerator;
