import { useState } from "react";
import { motion } from "framer-motion";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Copy, Download, Map, Plus, X, Globe, Clock, BarChart } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface SitemapUrl {
  loc: string;
  lastmod: string;
  changefreq: string;
  priority: string;
}

const SitemapGenerator = () => {
  const { toast } = useToast();
  const [baseUrl, setBaseUrl] = useState("https://");
  const [urls, setUrls] = useState<SitemapUrl[]>([
    { loc: "/", lastmod: new Date().toISOString().split('T')[0], changefreq: "weekly", priority: "1.0" }
  ]);

  const changefreqOptions = ["always", "hourly", "daily", "weekly", "monthly", "yearly", "never"];
  const priorityOptions = ["1.0", "0.9", "0.8", "0.7", "0.6", "0.5", "0.4", "0.3", "0.2", "0.1"];

  const addUrl = () => {
    setUrls([...urls, { 
      loc: "/new-page", 
      lastmod: new Date().toISOString().split('T')[0], 
      changefreq: "monthly", 
      priority: "0.5" 
    }]);
  };

  const removeUrl = (index: number) => {
    if (urls.length > 1) {
      setUrls(urls.filter((_, i) => i !== index));
    }
  };

  const updateUrl = (index: number, field: keyof SitemapUrl, value: string) => {
    const updated = [...urls];
    updated[index] = { ...updated[index], [field]: value };
    setUrls(updated);
  };

  const generateSitemap = () => {
    const cleanBaseUrl = baseUrl.replace(/\/$/, '');
    
    let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
    xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';
    xml += '  <!-- Sitemap generated by DigiSpark Tools -->\n';
    xml += '  <!-- https://digispark.com/tools -->\n\n';

    urls.forEach(url => {
      const fullUrl = url.loc.startsWith('http') ? url.loc : `${cleanBaseUrl}${url.loc.startsWith('/') ? '' : '/'}${url.loc}`;
      xml += '  <url>\n';
      xml += `    <loc>${fullUrl}</loc>\n`;
      if (url.lastmod) xml += `    <lastmod>${url.lastmod}</lastmod>\n`;
      if (url.changefreq) xml += `    <changefreq>${url.changefreq}</changefreq>\n`;
      if (url.priority) xml += `    <priority>${url.priority}</priority>\n`;
      xml += '  </url>\n';
    });

    xml += '</urlset>';
    return xml;
  };

  const sitemap = generateSitemap();

  const copyToClipboard = () => {
    navigator.clipboard.writeText(sitemap);
    toast({
      title: "Copied!",
      description: "Sitemap XML copied to clipboard",
    });
  };

  const downloadFile = () => {
    const blob = new Blob([sitemap], { type: "application/xml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "sitemap.xml";
    a.click();
    URL.revokeObjectURL(url);
    toast({
      title: "Downloaded!",
      description: "Sitemap.xml file downloaded successfully",
    });
  };

  const addCommonPages = () => {
    const commonPages = [
      { loc: "/about", changefreq: "monthly", priority: "0.8" },
      { loc: "/services", changefreq: "weekly", priority: "0.9" },
      { loc: "/contact", changefreq: "monthly", priority: "0.7" },
      { loc: "/blog", changefreq: "daily", priority: "0.8" },
      { loc: "/portfolio", changefreq: "weekly", priority: "0.8" },
      { loc: "/faq", changefreq: "monthly", priority: "0.6" },
    ];

    const newUrls = commonPages
      .filter(page => !urls.some(u => u.loc === page.loc))
      .map(page => ({
        ...page,
        lastmod: new Date().toISOString().split('T')[0]
      }));

    if (newUrls.length > 0) {
      setUrls([...urls, ...newUrls]);
      toast({
        title: "Pages Added!",
        description: `Added ${newUrls.length} common pages`,
      });
    } else {
      toast({
        title: "No New Pages",
        description: "All common pages are already added",
      });
    }
  };

  return (
    <Card className="border-yellow-400/20 bg-black/50 backdrop-blur-md">
      <CardContent className="p-6">
        <div className="flex items-center gap-3 mb-6">
          <div className="p-3 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-500">
            <Map className="w-6 h-6 text-white" />
          </div>
          <div>
            <h3 className="text-2xl font-bold text-white">XML Sitemap Generator</h3>
            <p className="text-gray-400 text-base">Create a valid XML sitemap to help search engines index your site</p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Configuration Section */}
          <div className="space-y-6">
            {/* Base URL */}
            <div className="space-y-2">
              <Label className="text-white text-base flex items-center gap-2">
                <Globe className="w-4 h-4 text-yellow-400" />
                Website Base URL
              </Label>
              <Input
                placeholder="https://yoursite.com"
                value={baseUrl}
                onChange={(e) => setBaseUrl(e.target.value)}
                className="bg-gray-800/50 text-white border-gray-700 text-base"
              />
            </div>

            {/* Quick Add */}
            <Button
              variant="outline"
              onClick={addCommonPages}
              className="w-full border-yellow-400/50 text-yellow-400 hover:bg-yellow-400/10"
            >
              <Plus className="w-4 h-4 mr-2" />
              Add Common Pages (About, Services, Contact, etc.)
            </Button>

            {/* URLs List */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <Label className="text-white text-base">URL Entries ({urls.length})</Label>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={addUrl}
                  className="border-yellow-400/50 text-yellow-400 hover:bg-yellow-400/10"
                >
                  <Plus className="w-4 h-4 mr-1" />
                  Add URL
                </Button>
              </div>

              <div className="max-h-96 overflow-y-auto space-y-3 pr-2">
                {urls.map((url, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="bg-gray-800/30 rounded-lg p-4 space-y-3 border border-gray-700/50"
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-yellow-400 font-mono text-base">URL #{index + 1}</span>
                      {urls.length > 1 && (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => removeUrl(index)}
                          className="text-red-400 hover:text-red-300 hover:bg-red-400/10"
                        >
                          <X className="w-4 h-4" />
                        </Button>
                      )}
                    </div>

                    <div className="grid grid-cols-1 gap-3">
                      <Input
                        placeholder="/page-path"
                        value={url.loc}
                        onChange={(e) => updateUrl(index, 'loc', e.target.value)}
                        className="bg-gray-900/50 text-white border-gray-600 text-base"
                      />
                      
                      <div className="grid grid-cols-3 gap-2">
                        <div>
                          <Label className="text-gray-400 text-sm flex items-center gap-1">
                            <Clock className="w-3 h-3" /> Last Modified
                          </Label>
                          <Input
                            type="date"
                            value={url.lastmod}
                            onChange={(e) => updateUrl(index, 'lastmod', e.target.value)}
                            className="bg-gray-900/50 text-white border-gray-600 text-base mt-1"
                          />
                        </div>
                        
                        <div>
                          <Label className="text-gray-400 text-sm">Frequency</Label>
                          <Select
                            value={url.changefreq}
                            onValueChange={(value) => updateUrl(index, 'changefreq', value)}
                          >
                            <SelectTrigger className="bg-gray-900/50 text-white border-gray-600 mt-1">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent className="bg-gray-900 border-gray-700">
                              {changefreqOptions.map(freq => (
                                <SelectItem key={freq} value={freq} className="text-white hover:bg-gray-800">
                                  {freq}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                        
                        <div>
                          <Label className="text-gray-400 text-sm flex items-center gap-1">
                            <BarChart className="w-3 h-3" /> Priority
                          </Label>
                          <Select
                            value={url.priority}
                            onValueChange={(value) => updateUrl(index, 'priority', value)}
                          >
                            <SelectTrigger className="bg-gray-900/50 text-white border-gray-600 mt-1">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent className="bg-gray-900 border-gray-700">
                              {priorityOptions.map(priority => (
                                <SelectItem key={priority} value={priority} className="text-white hover:bg-gray-800">
                                  {priority}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          </div>

          {/* Preview Section */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <Label className="text-white text-base flex items-center gap-2">
                <Map className="w-4 h-4 text-yellow-400" />
                Generated sitemap.xml
              </Label>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={copyToClipboard}
                  className="border-yellow-400/50 text-yellow-400 hover:bg-yellow-400/10"
                >
                  <Copy className="w-4 h-4 mr-1" />
                  Copy
                </Button>
                <Button
                  size="sm"
                  onClick={downloadFile}
                  className="bg-yellow-400 hover:bg-yellow-300 text-black"
                >
                  <Download className="w-4 h-4 mr-1" />
                  Download
                </Button>
              </div>
            </div>

            <Textarea
              value={sitemap}
              readOnly
              className="h-80 font-mono text-base bg-gray-900/50 text-cyan-400 border-gray-700"
            />

            <div className="bg-gray-800/30 rounded-lg p-4 border border-gray-700/50">
              <h4 className="text-yellow-400 font-semibold mb-2 text-base">📌 How to Use</h4>
              <ol className="text-gray-300 space-y-1 list-decimal list-inside text-base">
                <li>Add all important pages to the sitemap</li>
                <li>Download the generated sitemap.xml file</li>
                <li>Upload it to your website's root directory</li>
                <li>Submit the sitemap URL to Google Search Console</li>
              </ol>
            </div>

            <div className="bg-blue-900/20 rounded-lg p-4 border border-blue-500/30">
              <h4 className="text-blue-400 font-semibold mb-2 text-base">💡 Priority Guide</h4>
              <ul className="text-gray-300 space-y-1 text-base">
                <li><span className="text-yellow-400">1.0</span> - Homepage</li>
                <li><span className="text-yellow-400">0.8-0.9</span> - Important pages (Services, Products)</li>
                <li><span className="text-yellow-400">0.5-0.7</span> - Regular pages (Blog, About)</li>
                <li><span className="text-yellow-400">0.1-0.4</span> - Less important pages</li>
              </ul>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default SitemapGenerator;
