// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtoabocyojjmivziamtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0b2Fib2N5b2pqbWl2emlhbXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzNDk2MDEsImV4cCI6MjA4MTkyNTYwMX0._jldTS1ncSK4JXUTFGdrY0jgpHKlVI5wD5i9xl8GufI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
